# frozen_string_literal: true

module Typesense
end

require 'uri'
require_relative 'typesense/version'
require_relative 'typesense/configuration'
require_relative 'typesense/client'
require_relative 'typesense/api_call'
require_relative 'typesense/collections'
require_relative 'typesense/collection'
require_relative 'typesense/documents'
require_relative 'typesense/document'
require_relative 'typesense/overrides'
require_relative 'typesense/override'
require_relative 'typesense/synonyms'
require_relative 'typesense/synonym'
require_relative 'typesense/aliases'
require_relative 'typesense/alias'
require_relative 'typesense/keys'
require_relative 'typesense/key'
require_relative 'typesense/multi_search'
require_relative 'typesense/analytics'
require_relative 'typesense/analytics_rules'
require_relative 'typesense/analytics_rule'
require_relative 'typesense/presets'
require_relative 'typesense/preset'
require_relative 'typesense/debug'
require_relative 'typesense/health'
require_relative 'typesense/metrics'
require_relative 'typesense/stats'
require_relative 'typesense/operations'
require_relative 'typesense/error'
